Add unit tests for com.sia.hunter.helper.StringHelper
Diffblue-benchmarks/Siaorg-sia-task pull request #2
Opened 2019-08-06 13:46 UTC by shafi-1

I've analysed your codebase and noticed that `com.sia.hunter.helper.StringHelper` is not fully tested.
I've written some tests for the methods in this class with the help of [Diffblue Cover](https://www.diffblue.com/opensource).

Hopefully, these tests will help you detect any regressions caused by future code changes. If you would find it useful to have additional tests written for this repository, I would be more than happy to look at other classes that you consider important in a subsequent PR.

2019-08-06 15:36 UTC, paulkennethkent approved these changes

2019-08-06 15:41 UTC, petersear requested changes
This PR includes commits for the tests added for `com.sia.hunter.helper.OnlineTaskHelper` (which has already been merged in an earlier PR.)
btw I think that was merged to the wrong location:
sia-task/sia-task-hunter/src/main/test/com/sia/hunter/OnlineTaskHelperTest.java
when it should have probably gone to:
sia-task/sia-task-hunter/src/test/com/sia/hunter/helper/OnlineTaskHelperTest.java
(please correct me if I'm mistaken. If not it could be moved as part of this PR)

The proposed test class here:
sia-task/sia-task-hunter/src/main/test/com/sia/hunter/StringHelperTest.java
should probably go to:
sia-task/sia-task-hunter/src/test/com/sia/hunter/helper/StringHelperTest.java
(again, unless I'm mistaken)

2019-08-06 15:41 UTC, petersear commented on sia-task-hunter/src/main/test/com/sia/hunter/StringHelperTest.java
> +import java.util.*;
Avoid importing wildcards. Import the specific classes required.

2019-08-06 15:41 UTC, petersear commented on sia-task-hunter/src/main/test/com/sia/hunter/StringHelperTest.java
> +
Remove blank line

2019-08-06 15:41 UTC, petersear commented on sia-task-hunter/src/main/test/com/sia/hunter/StringHelperTest.java
> +package com.sia.hunter;
Shouldn't package be `com.sia.hunter.helper`? (as in the source class)
If so, this would also apply to `OnlineTaskHelper`

2019-08-06 15:41 UTC, petersear commented on sia-task-hunter/src/main/test/com/sia/hunter/StringHelperTest.java
> +import com.sia.hunter.helper.StringHelper;
Is this import needed? I'd think not if the package is `com.sia.hunter.helper` (as suggested elsewhere)

2019-08-07 09:24 UTC, petersear requested changes
The contents of the files looks good to me now but the changes to pom.xml and OnlineTaskHelperTest.java were previously merged into the repo so these changes should not show pom changes (assuming there as no change between the two PRs) and should show OnlineTaskHelperTest.java being removed from the previous location.
The commit on this branch is added on top of commits from May and does not include your previous work so I think you need to resync the branch for these changes to look correct.

2019-08-07 15:30 UTC, petersear approved these changes

2019-08-22 10:31 UTC, merged